# -*- coding: utf-8 -*-
"""Movie_Recommendation_System1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1frwYsaMDA81KRQnTbp_ELU44mf5Idcol
"""

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
organizations_tmdb_tmdb_movie_metadata_path = kagglehub.dataset_download('organizations/tmdb/tmdb-movie-metadata')
rounakbanik_the_movies_dataset_path = kagglehub.dataset_download('rounakbanik/the-movies-dataset')

print('Data source import complete.')

"""# **Movie Recommendation System Using Content-Based and Collaborative Filtering**

## **Project Overview**
Sistem rekomendasi ini dikembangkan untuk memberikan rekomendasi film berdasarkan dua pendekatan utama:

1. **Content-Based Filtering**  
   - Menggunakan **TF-IDF Vectorization** dan **Cosine Similarity** untuk menemukan film yang memiliki kemiripan berdasarkan metadata seperti genre, sutradara, dan kata kunci.
   - Pendekatan ini cocok untuk pengguna yang ingin menemukan film serupa dengan yang telah mereka tonton.
   - Model dievaluasi dengan **NDCG@10 (Normalized Discounted Cumulative Gain)** untuk mengukur akurasi prediksi.

2. **Collaborative Filtering (Matrix Factorization - SVD)**  
   - Menggunakan teknik **Singular Value Decomposition (SVD)** untuk memprediksi rating film berdasarkan interaksi pengguna sebelumnya.
   - Pendekatan ini bekerja dengan menganalisis pola rating pengguna lain yang memiliki preferensi serupa.
   - Model dievaluasi dengan **Root Mean Square Error (RMSE)** dan **Mean Absolute Error (MAE)** untuk mengukur akurasi prediksi.

## **Load Dataset**
"""

# Import library yang diperlukan
import ast
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from ast import literal_eval
from collections import Counter
from sklearn.metrics import ndcg_score
from surprise import Reader, Dataset, SVD
from sklearn.metrics.pairwise import linear_kernel
from surprise.model_selection import cross_validate
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer

# Membaca dataset
credits_df = pd.read_csv('../input/tmdb-movie-metadata/tmdb_5000_credits.csv')
movies_df = pd.read_csv('../input/tmdb-movie-metadata/tmdb_5000_movies.csv')
ratings_df = pd.read_csv('../input/the-movies-dataset/ratings_small.csv')     # Data tentang rating pengguna

"""## **Data Understanding**

Pada tahap **Data Understanding**, kita mengeksplorasi tiga dataset utama: **movies**, **credits**, dan **ratings**. Informasi umum dari masing-masing dataset ditampilkan untuk memahami struktur, jumlah data, serta tipe variabel yang tersedia. Setelah itu, dilakukan penggabungan dataset **movies** dan **credits** berdasarkan kolom **id** untuk menyatukan informasi pemeran dan kru film.  

Statistik deskriptif digunakan untuk mendapatkan insight awal, seperti rata-rata vote, durasi film terpanjang, serta film dengan pendapatan tertinggi. Visualisasi dilakukan untuk menganalisis distribusi vote dan rating pengguna, hubungan antara popularitas dan pendapatan film, jumlah film berdasarkan bahasa asli, serta korelasi antara runtime dan vote average. Selain itu, perusahaan produksi dengan jumlah film terbanyak juga dianalisis. Terakhir, heatmap korelasi digunakan untuk memahami hubungan antar variabel penting dalam dataset.
"""

# ==================== Analisis DataFrame movies_df ====================

# 1. Jumlah data (baris dan kolom)
print("📌 Jumlah baris dan kolom (movies_df):")
print(movies_df.shape)
print()

# 2. Kondisi data
print("📌 Informasi struktur data (movies_df):")
print(movies_df.info())
print()

print("📌 Jumlah missing value tiap kolom (movies_df):")
print(movies_df.isnull().sum())
print()

print("📌 Jumlah data duplikat (movies_df):")
print(movies_df.drop(columns=['genres'], errors='ignore').duplicated().sum())  # Hindari error karena kolom list
print()

# 3. Statistik numerik
print("📌 Statistik deskriptif numerik (movies_df):")
print(movies_df.describe(include='number'))
print()


# ==================== Analisis DataFrame credits_df ====================

print("📌 Jumlah baris dan kolom (credits_df):")
print(credits_df.shape)
print()

print("📌 Informasi struktur data (credits_df):")
print(credits_df.info())
print()

print("📌 Jumlah missing value tiap kolom (credits_df):")
print(credits_df.isnull().sum())
print()

print("📌 Jumlah data duplikat (credits_df):")
print(credits_df.drop(columns=['cast', 'crew'], errors='ignore').duplicated().sum())
print()

print("📌 Statistik deskriptif numerik (credits_df):")
print(credits_df.describe(include='number'))
print()


# ==================== Analisis DataFrame ratings_df ====================

print("📌 Jumlah baris dan kolom (ratings_df):")
print(ratings_df.shape)
print()

print("📌 Informasi struktur data (ratings_df):")
print(ratings_df.info())
print()

print("📌 Jumlah missing value tiap kolom (ratings_df):")
print(ratings_df.isnull().sum())
print()

print("📌 Jumlah data duplikat (ratings_df):")
print(ratings_df.duplicated().sum())
print()

print("📌 Statistik deskriptif numerik (ratings_df):")
print(ratings_df.describe(include='number'))
print()

# Pilih hanya kolom numerik dari movies_df
numeric_cols = movies_df.select_dtypes(include=['float64', 'int64']).columns

# Ukuran plot
plt.figure(figsize=(15, 6 * len(numeric_cols)))

# Loop dan buat boxplot untuk tiap kolom numerik
for i, col in enumerate(numeric_cols, 1):
    plt.subplot(len(numeric_cols), 1, i)
    sns.boxplot(data=movies_df, x=col, color='skyblue')
    plt.title(f'Boxplot: {col}', fontsize=14)
    plt.xlabel('')

plt.tight_layout()
plt.show()

# Pilih hanya kolom numerik dari ratings_df
numeric_cols = ratings_df.select_dtypes(include=['float64', 'int64']).columns

# Ukuran plot
plt.figure(figsize=(15, 6 * len(numeric_cols)))

# Loop dan buat boxplot untuk tiap kolom numerik
for i, col in enumerate(numeric_cols, 1):
    plt.subplot(len(numeric_cols), 1, i)
    sns.boxplot(data=ratings_df, x=col, color='skyblue')
    plt.title(f'Boxplot: {col}', fontsize=14)
    plt.xlabel('')

plt.tight_layout()
plt.show()

# Menampilkan informasi umum dataset
print("\nInformasi Dataset Film:")
print(movies_df.info())

# Menampilkan informasi umum dataset
print("\nInformasi Dataset Credit:")
print(credits_df.info())

print("\nInformasi Dataset Rating:")
print(ratings_df.info())

"""### **Informasi Dataset Film, Kredit, dan Rating**

#### **Dataset Film (`movies_df`)**
Dataset ini berisi informasi terkait berbagai film, termasuk anggaran, genre, dan rating pengguna.

##### **Kolom dalam Dataset:**
| No | Nama Kolom             | Tipe Data | Deskripsi |
|----|------------------------|----------|-----------|
| 1  | `budget`               | int64    | Total anggaran produksi film. |
| 2  | `genres`               | object   | Daftar genre film dalam format list atau string. |
| 3  | `homepage`             | object   | URL situs resmi film. |
| 4  | `id`                   | int64    | ID unik film (terhubung dengan dataset lain). |
| 5  | `keywords`             | object   | Kata kunci atau tag yang mendeskripsikan film. |
| 6  | `original_language`    | object   | Bahasa asli film. |
| 7  | `original_title`       | object   | Judul asli film sebelum diterjemahkan. |
| 8  | `overview`             | object   | Ringkasan singkat cerita film. |
| 9  | `popularity`           | float64  | Skor numerik yang mengindikasikan popularitas film. |
| 10 | `production_companies` | object   | Nama perusahaan produksi film. |
| 11 | `production_countries` | object   | Negara tempat film diproduksi. |
| 12 | `release_date`         | object   | Tanggal rilis film. |
| 13 | `revenue`              | int64    | Total pendapatan yang dihasilkan film. |
| 14 | `runtime`              | float64  | Durasi film dalam menit. |
| 15 | `spoken_languages`     | object   | Bahasa yang digunakan dalam film. |
| 16 | `status`               | object   | Status film (contoh: "Released", "Rumored"). |
| 17 | `tagline`              | object   | Slogan atau tagline resmi film. |
| 18 | `title`                | object   | Judul resmi film. |
| 19 | `vote_average`         | float64  | Nilai rata-rata rating film berdasarkan ulasan pengguna. |
| 20 | `vote_count`           | int64    | Jumlah total ulasan yang diberikan pengguna. |

---

#### **Dataset Kredit (`credits_df`)**
Dataset ini berisi informasi mengenai pemeran dan kru film.

##### **Kolom dalam Dataset:**
| No | Nama Kolom | Tipe Data | Deskripsi |
|----|-----------|----------|-----------|
| 1  | `movie_id` | int64   | ID unik film yang berhubungan dengan dataset `movies_df`. |
| 2  | `title`    | object  | Judul film. |
| 3  | `cast`     | object  | Daftar aktor utama dan pemeran pendukung. |
| 4  | `crew`     | object  | Daftar kru film, termasuk sutradara dan penulis. |

---

#### **Dataset Rating (`ratings_df`)**
Dataset ini berisi informasi rating yang diberikan oleh pengguna terhadap film tertentu.

##### **Kolom dalam Dataset:**
| No | Nama Kolom  | Tipe Data | Deskripsi |
|----|------------|----------|-----------|
| 1  | `userId`   | int64    | ID unik pengguna yang memberikan rating. |
| 2  | `movieId`  | int64    | ID unik film yang diberikan rating (terhubung dengan `movies_df`). |
| 3  | `rating`   | float64  | Skor rating yang diberikan oleh pengguna (biasanya dalam rentang 1-5). |
| 4  | `timestamp`| int64    | Waktu saat pengguna memberikan rating (format Unix Timestamp). |

"""

# Menampilkan ringkasan statistik data numerik
print("\nRingkasan Statistik Dataset Film:")
print(movies_df.describe())

print("\nRingkasan Statistik Dataset Rating:")
print(ratings_df.describe())

# Mengubah nama kolom untuk konsistensi
credits_df.columns = ['id', 'title', 'cast', 'crew']

# Melakukan merge berdasarkan kolom 'id' untuk menghindari duplikasi judul
movies_df = movies_df.merge(credits_df, on='id')

# Menghapus salah satu kolom title yang duplikat (misalnya, 'title_y')
movies_df = movies_df.drop(columns=['title_y'])

# Mengganti nama 'title_x' kembali menjadi 'title' agar lebih jelas
movies_df = movies_df.rename(columns={'title_x': 'title'})

# Menampilkan informasi dataset hasil merge
print(movies_df.info())

movies_df.head()

print("\nInsight dari Statistik Deskriptif:")
print(f"- Rata-rata vote film: {movies_df['vote_average'].mean():.2f}")
print(f"- Durasi film terpanjang: {movies_df['runtime'].max()} menit")
print(f"- Film dengan pendapatan tertinggi: {movies_df.loc[movies_df['revenue'].idxmax(), 'title']} dengan pendapatan ${movies_df['revenue'].max():,.2f}")

plt.figure(figsize=(12,5))
sns.histplot(movies_df['vote_average'].dropna(), bins=30, kde=True)
plt.title("Distribusi Rata-rata Vote Film")
plt.xlabel("Vote Average")
plt.ylabel("Frekuensi")
plt.show()

plt.figure(figsize=(12,5))
sns.histplot(ratings_df['rating'].dropna(), bins=30, kde=True, color='orange')
plt.title("Distribusi Rating Pengguna")
plt.xlabel("Rating")
plt.ylabel("Frekuensi")
plt.show()

# Visualisasi hubungan antara popularitas dan pendapatan film
plt.figure(figsize=(12,6))
sns.scatterplot(data=movies_df, x='popularity', y='revenue', alpha=0.5)
plt.title("Hubungan antara Popularitas dan Pendapatan Film")
plt.xlabel("Popularitas")
plt.ylabel("Pendapatan (Revenue)")
plt.show()

# Visualisasi jumlah film berdasarkan bahasa asli
plt.figure(figsize=(12,6))
sns.countplot(y=movies_df['original_language'], order=movies_df['original_language'].value_counts().index, palette='viridis')
plt.title("Jumlah Film Berdasarkan Bahasa Asli")
plt.xlabel("Jumlah Film")
plt.ylabel("Bahasa Asli")
plt.show()

# Visualisasi hubungan antara runtime dan vote_average
plt.figure(figsize=(12,6))
sns.scatterplot(data=movies_df, x='runtime', y='vote_average', alpha=0.5, color='red')
plt.title("Hubungan antara Durasi Film dan Rata-rata Vote")
plt.xlabel("Runtime (menit)")
plt.ylabel("Vote Average")
plt.show()

# Visualisasi top 10 production companies dengan jumlah film terbanyak
# Mengambil data perusahaan produksi
production_companies = movies_df['production_companies'].dropna().apply(lambda x: [i['name'] for i in ast.literal_eval(x)] if isinstance(x, str) else [])
all_companies = [company for sublist in production_companies for company in sublist]
top_companies = pd.DataFrame(Counter(all_companies).most_common(10), columns=['Company', 'Film Count'])

plt.figure(figsize=(12,6))
sns.barplot(data=top_companies, x='Film Count', y='Company', palette='coolwarm')
plt.title("Top 10 Production Companies dengan Jumlah Film Terbanyak")
plt.xlabel("Jumlah Film")
plt.ylabel("Production Company")
plt.show()

plt.figure(figsize=(10,6))
sns.heatmap(movies_df[['budget', 'popularity', 'revenue', 'runtime', 'vote_average']].corr(), annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Correlation Heatmap antara Variabel Penting")
plt.show()

"""**Insight dari Visualisasi Data Film**

**1. Hubungan antara Popularitas dan Pendapatan Film**
- Film dengan popularitas tinggi cenderung memiliki pendapatan lebih besar, meskipun ada beberapa outlier yang menghasilkan pendapatan tinggi meskipun popularitasnya sedang.  
- Sebagian besar film memiliki popularitas rendah hingga sedang, dengan pendapatan yang relatif kecil.  

**2. Distribusi Rata-rata Vote Film**
- Distribusi rating cenderung normal dengan puncak pada nilai **6-7**, menunjukkan bahwa sebagian besar film dinilai cukup baik.  
- Rating sangat rendah (<2) dan sangat tinggi (>9) jarang terjadi.  

**3. Distribusi Rating Pengguna**
- Mayoritas rating berkisar antara **3-5**, dengan puncak pada **4**, mengindikasikan kepuasan pengguna.  
- Rating di bawah 3 lebih jarang terjadi, menunjukkan sedikit film yang benar-benar buruk menurut pengguna.  

**4. Correlation Heatmap**
- **Budget dan revenue (0.73)** serta **popularity dan revenue (0.64)** menunjukkan hubungan kuat, artinya film dengan anggaran besar dan popularitas tinggi cenderung menghasilkan lebih banyak pendapatan.  
- **Budget dan popularity (0.51)** memiliki korelasi moderat, menandakan bahwa film dengan anggaran besar sering kali lebih populer.  
- **Vote average tidak memiliki korelasi kuat** dengan faktor lain, menunjukkan bahwa rating pengguna tidak terlalu dipengaruhi oleh budget, popularitas, atau runtime.  

**5. Hubungan antara Durasi Film dan Rata-rata Vote**
- Tidak ada pola yang jelas antara runtime film dan rating rata-rata.  
- Film dengan runtime panjang (>200 menit) terkadang mendapatkan rating tinggi, tetapi secara keseluruhan, durasi bukan faktor utama dalam menentukan rating.  

**Kesimpulan**
Faktor utama yang mempengaruhi pendapatan film adalah **budget dan popularitas**, sementara **rating rata-rata tidak memiliki hubungan kuat dengan variabel lain**. Mayoritas film mendapat rating **sedang hingga tinggi**, mencerminkan kepuasan pengguna secara umum. **Runtime film tidak berperan besar dalam menentukan rating**, sehingga faktor lain seperti **cerita, aktor, atau genre** kemungkinan lebih berpengaruh.

## **Data Preparation**

### **1. Pembersihan & Penggabungan Data**
- Mengubah nama kolom, menggabungkan `movies_df` & `credits_df`, serta menghapus duplikasi judul.

### **2. Menghitung Rating Berbobot**
- Menggunakan **formula IMDB** berdasarkan rata-rata rating (`vote_average`) dan jumlah vote (`vote_count`).
- Memfilter film dengan `vote_count` di atas kuantil ke-90.

### **3. Kesamaan Sinopsis (TF-IDF)**
- Menggunakan **TF-IDF Vectorizer** untuk mengubah `overview` menjadi vektor numerik.
- Menghitung **Cosine Similarity** antarfilm berdasarkan sinopsis.

### **4. Ekstraksi & Normalisasi Fitur**
- Mengambil `cast`, `crew`, `keywords`, dan `genres`.
- Menentukan sutradara, aktor utama, dan genre utama.
- Membersihkan teks agar lebih konsisten.
"""

# Menghitung nilai rata-rata vote pada dataset film
average_vote = movies_df['vote_average'].mean()
average_vote

# Menghitung nilai kuantil ke-90 dari jumlah vote untuk menentukan ambang batas popularitas film
vote_threshold = movies_df['vote_count'].quantile(0.9)
vote_threshold

# Memfilter film dengan jumlah vote di atas ambang batas (vote_threshold)
top_rated_movies = movies_df.copy().loc[movies_df['vote_count'] >= vote_threshold]
print("Jumlah film yang memenuhi kriteria:", top_rated_movies.shape)

def calculate_weighted_rating(movie, m=vote_threshold, C=average_vote):
    """
    Menghitung rating berbobot berdasarkan formula IMDB.

    Parameter:
    movie (Series): Data satu film yang berisi 'vote_count' dan 'vote_average'.
    m (int): Ambang batas jumlah vote minimum agar film dipertimbangkan.
    C (float): Rata-rata rating dari seluruh film.

    Returns:
    float: Rating berbobot untuk film tersebut.
    """
    v = movie['vote_count']  # Jumlah vote film
    R = movie['vote_average']  # Rata-rata rating film

    # Menghitung rating berbobot menggunakan formula IMDB
    return (v / (v + m) * R) + (m / (m + v) * C)

# Menambahkan kolom 'score' yang berisi perhitungan rating berbobot menggunakan fungsi calculate_weighted_rating
top_rated_movies['score'] = top_rated_movies.apply(calculate_weighted_rating, axis=1)

movies_df.head()

# Mengurutkan film berdasarkan nilai 'score' dari yang tertinggi ke terendah
top_rated_movies = top_rated_movies.sort_values('score', ascending=False)

# Menampilkan 10 film dengan skor tertinggi beserta informasi terkait
top_rated_movies[['title', 'vote_count', 'vote_average', 'score']].head(10)

# Mengurutkan data film berdasarkan popularitas tertinggi
sorted_movies_by_popularity = movies_df.sort_values('popularity', ascending=False)

# Menentukan ukuran plot (lebar dan tinggi)
plt.figure(figsize=(12, 6))

# Membuat diagram batang horizontal untuk 6 film terpopuler
plt.barh(sorted_movies_by_popularity['title'].head(6),
         sorted_movies_by_popularity['popularity'].head(6),
         align='center', color='lightcoral')

# Membalikkan sumbu y agar film dengan popularitas tertinggi berada di atas
plt.gca().invert_yaxis()

# Menambahkan label untuk sumbu X (Popularitas)
plt.xlabel("Popularity", fontsize=12)

# Menambahkan judul pada grafik
plt.title("Top 6 Most Popular Movies", fontsize=14)

# Menampilkan grafik
plt.show()

movies_df['overview'].head(5)

# Inisialisasi objek TF-IDF Vectorizer dengan menghilangkan stop words dalam bahasa Inggris
tfidf_vectorizer = TfidfVectorizer(stop_words='english')

# Mengganti nilai NaN dalam kolom 'overview' dengan string kosong untuk menghindari error
movies_df['overview'] = movies_df['overview'].fillna('')

# Membangun matriks TF-IDF dengan menyesuaikan dan mentransformasikan teks dalam kolom 'overview'
tfidf_matrix = tfidf_vectorizer.fit_transform(movies_df['overview'])

# Menampilkan dimensi dari matriks TF-IDF yang telah dibuat
print(f"Dimensi matriks TF-IDF: {tfidf_matrix.shape}")

movies_df.head()

# Menghitung matriks kesamaan kosinus antara dokumen
cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)

# Membuat peta balik (reverse map) antara indeks dan judul film
indices = pd.Series(movies_df.index, index=movies_df['title']).drop_duplicates()

# Daftar fitur yang ingin diubah dari string menjadi objek Python
features = ['cast', 'crew', 'keywords', 'genres']

# Melakukan parsing string yang berisi fitur-fitur menjadi objek Python yang sesuai
for feature in features:
    # Menggunakan literal_eval untuk mengonversi string menjadi list atau dictionary
    movies_df[feature] = movies_df[feature].apply(literal_eval)

# Fungsi untuk mendapatkan nama sutradara dari fitur crew
# Jika sutradara tidak ditemukan, akan mengembalikan NaN
def get_director(x):
    # Mengiterasi setiap elemen dalam crew
    for i in x:
        # Memeriksa jika peran dalam crew adalah 'Director'
        if i['job'] == 'Director':
            return i['name']
    # Jika tidak ditemukan sutradara, mengembalikan NaN
    return np.nan

# Fungsi untuk mengembalikan 3 elemen teratas dari list, atau seluruh list jika jumlah elemen kurang dari 3
def get_list(x):
    # Memeriksa apakah x adalah sebuah list
    if isinstance(x, list):
        # Membuat daftar nama dengan mengambil elemen 'name' dari setiap dictionary dalam list
        names = [i['name'] for i in x]

        # Memeriksa apakah jumlah elemen lebih dari 3. Jika ya, hanya mengembalikan 3 elemen pertama
        if len(names) > 3:
            names = names[:3]
        return names

    # Jika x bukan list atau data rusak, mengembalikan list kosong
    return []

# Menambahkan fitur baru untuk sutradara, cast, genre, dan kata kunci dalam bentuk yang sesuai

# Menggunakan fungsi get_director untuk mengambil nama sutradara dari kolom 'crew'
movies_df['director'] = movies_df['crew'].apply(get_director)

# Daftar fitur yang ingin diolah
features = ['cast', 'keywords', 'genres']

# Iterasi untuk setiap fitur dalam daftar 'features'
for feature in features:
    # Menggunakan fungsi get_list untuk mengolah data list dalam setiap fitur
    movies_df[feature] = movies_df[feature].apply(get_list)

# Menampilkan fitur baru untuk 3 film pertama dalam dataset
movies_df[['title', 'cast', 'director', 'keywords', 'genres']].head(3)

# Fungsi untuk mengubah semua string menjadi huruf kecil dan menghapus spasi pada nama
def clean_data(x):
    # Mengecek jika x adalah list
    if isinstance(x, list):
        # Mengubah semua elemen dalam list menjadi huruf kecil dan menghapus spasi
        return [str.lower(i.replace(" ", "")) for i in x]
    else:
        # Jika x adalah string, mengubahnya menjadi huruf kecil dan menghapus spasi
        if isinstance(x, str):
            return str.lower(x.replace(" ", ""))
        else:
            # Jika x bukan string atau list, mengembalikan string kosong
            return ''

# Menerapkan fungsi clean_data ke fitur yang ada dalam DataFrame
features = ['cast', 'keywords', 'director', 'genres']

# Iterasi melalui setiap fitur yang ada dalam list 'features'
for feature in features:
    # Menerapkan fungsi clean_data pada setiap elemen dalam kolom feature
    movies_df[feature] = movies_df[feature].apply(clean_data)

# Fungsi untuk membuat 'soup' dari fitur keywords, cast, director, dan genres
def create_soup(x):
    # Menggabungkan keywords, cast, director, dan genres menjadi satu string
    return ' '.join(x['keywords']) + ' ' + ' '.join(x['cast']) + ' ' + x['director'] + ' ' + ' '.join(x['genres'])

# Menerapkan fungsi create_soup ke setiap baris DataFrame untuk membuat kolom 'soup'
movies_df['soup'] = movies_df.apply(create_soup, axis=1)

# Membuat objek CountVectorizer dengan mengabaikan stop words bahasa Inggris
count = CountVectorizer(stop_words='english')

# Membuat matriks hitung dari kolom 'soup' yang berisi gabungan fitur keywords, cast, director, dan genres
count_matrix = count.fit_transform(movies_df['soup'])

# Menghitung matriks Cosine Similarity berdasarkan matriks hitung (count_matrix)
cosine_sim2 = cosine_similarity(count_matrix, count_matrix)

# Mereset indeks dari DataFrame utama movies_df
movies_df = movies_df.reset_index()

# Membuat pemetaan balik (reverse mapping) antara indeks dan judul film
indices = pd.Series(movies_df.index, index=movies_df['title'])

"""## **Modeling Content Based Filtering**

Pendekatan ini menggunakan Content-Based Filtering untuk memberikan rekomendasi film berdasarkan kemiripan kontennya. Model ini membandingkan deskripsi film dan fitur lainnya, seperti sutradara, pemeran, genre, dan kata kunci, untuk menemukan film yang memiliki karakteristik serupa.

Data diformat dengan membersihkan teks, mengubah string menjadi daftar untuk fitur seperti genre dan pemeran, serta menggabungkan informasi relevan ke dalam satu kolom ('soup'). Dua teknik utama yang digunakan adalah TF-IDF Vectorizer untuk mengolah sinopsis film dan CountVectorizer untuk fitur tambahan. Dengan menggunakan Cosine Similarity, sistem dapat menghitung tingkat kemiripan antar film.

Model ini memungkinkan pengguna mendapatkan rekomendasi film yang relevan berdasarkan film yang sudah mereka tonton atau pilih sebelumnya, dengan hasil yang lebih akurat dibandingkan pendekatan berbasis metadata sederhana.
"""

def get_recommendation(judul, cosine_sim=cosine_sim2, k=10):
    # Ambil indeks dari film input
    idx = indices[judul]

    # Ambil skor kemiripan dan urutkan secara menurun
    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:k+1]  # Ambil k film yang paling mirip (tanpa film itu sendiri)

    # Ekstrak indeks dan skor kemiripan dari hasil
    movie_indices = [i[0] for i in sim_scores]
    movie_scores = [i[1] for i in sim_scores]

    # Ambil genre dari film input
    input_genres_raw = movies_df.loc[idx, 'genres']
    input_genres = set(input_genres_raw) if isinstance(input_genres_raw, list) else set()

    # Inisialisasi list untuk menyimpan hasil
    titles, predicted_genres, matched_genres = [], [], []
    relevance_scores = []  # Digunakan untuk perhitungan NDCG

    # Hitung metrik untuk setiap film rekomendasi
    for i in movie_indices:
        # Ambil genre dari film hasil rekomendasi
        rec_genres_raw = movies_df.loc[i, 'genres']
        rec_genres = set(rec_genres_raw) if isinstance(rec_genres_raw, list) else set()

        # Hitung irisan (genre yang cocok)
        intersection = input_genres & rec_genres

        # Hitung skor relevansi berdasarkan jumlah genre yang cocok
        relevance_score = len(intersection)

        # Simpan hasil
        titles.append(movies_df.loc[i, 'title'])
        predicted_genres.append(list(rec_genres))
        matched_genres.append(list(intersection))
        relevance_scores.append(relevance_score)

    # Hitung NDCG@K (Normalized Discounted Cumulative Gain)
    ideal_relevance = sorted(relevance_scores, reverse=True)
    ndcg = ndcg_score([ideal_relevance], [relevance_scores])

    # Buat DataFrame hasil rekomendasi
    recommendations = pd.DataFrame({
        'Title': titles,
        'Similarity Score': movie_scores,
        'Predicted Genre': predicted_genres,
        'Matched Genres': matched_genres,
        'Relevance Score': relevance_scores,  # Jumlah genre yang cocok
        'Input Genre': [list(input_genres)] * len(movie_indices)
    })

    # Tampilkan metrik evaluasi
    print(f"Metrik Evaluasi untuk '{judul}':")
    print(f"- NDCG@{k}: {ndcg:.4f}")

    return recommendations

get_recommendation('The Dark Knight Rises', cosine_sim2).loc[:]

get_recommendation('The Godfather', cosine_sim2).loc[:]

"""## **Modeling Collaborative Based Filtering**

Pendekatan ini menggunakan Collaborative Filtering untuk memberikan rekomendasi berdasarkan interaksi pengguna dengan film. Model ini memanfaatkan pola rating yang diberikan oleh pengguna lain dengan preferensi serupa untuk memprediksi film yang mungkin disukai oleh pengguna tertentu.

Dataset diproses dengan membangun matriks pengguna-film yang berisi rating yang diberikan oleh masing-masing pengguna. Teknik Singular Value Decomposition (SVD) digunakan untuk mendekomposisi matriks ini dan mengidentifikasi pola tersembunyi dalam preferensi pengguna.

Evaluasi model dilakukan dengan teknik cross-validation menggunakan Root Mean Square Error (RMSE) dan Mean Absolute Error (MAE) untuk mengukur akurasi prediksi. Setelah model dilatih, sistem dapat memberikan rekomendasi film kepada pengguna berdasarkan prediksi rating tertinggi untuk film yang belum mereka tonton.

Pendekatan ini sangat efektif karena mampu menangkap hubungan implisit antar pengguna dan film, memungkinkan sistem untuk merekomendasikan film yang relevan meskipun tidak memiliki metadata yang sama dengan film yang sudah ditonton oleh pengguna.
"""

# Membuat objek Reader untuk membaca data rating
reader = Reader()

# Memuat dataset dari DataFrame (pastikan ratings_df sudah tersedia)
data = Dataset.load_from_df(ratings_df[['userId', 'movieId', 'rating']], reader)

# Membagi dataset menjadi beberapa lipatan (folds) untuk cross-validation
svd = SVD()
# Melakukan cross-validation untuk mengukur akurasi model dengan 5 fold
cross_validate(svd, data, cv=5, verbose=True)

# Melatih model SVD dengan dataset penuh
trainset = data.build_full_trainset()
svd.fit(trainset)

def get_user_recommendations(user_id, svd_model, top_n=10):
    # 1. Get movies watched by user
    movies_watched = ratings_df[ratings_df['userId'] == user_id]

    if movies_watched.empty:
        print(f"User {user_id} has not watched any movies.")
        return None, None

    # 2. Process watched movies
    watched_info = movies_watched.merge(movies_df, left_on='movieId', right_on='id', how='left')
    watched_info = watched_info.drop_duplicates(subset=['title'])
    watched_info['rating'] = pd.to_numeric(watched_info['rating'], errors='coerce')
    watched_info = watched_info.sort_values(by='rating', ascending=False).head(11)

    # Filter out NaN titles for watched movies
    watched_info = watched_info[watched_info['title'].notna()]

    # 3. Create watched movies DataFrame
    watched_df = pd.DataFrame({
        'Title': watched_info['title'],
        'Genres': watched_info['genres'].apply(lambda x: ', '.join(x) if isinstance(x, list) else 'Unknown'),
        'User Rating': watched_info['rating']
    })

    # 4. Get movies not watched
    movies_not_watched = movies_df[~movies_df['id'].isin(movies_watched['movieId'])]

    # 5. Predict ratings for unwatched movies
    predicted_ratings = [svd_model.predict(user_id, movie_id).est for movie_id in movies_not_watched['id']]
    movies_not_watched['predicted_rating'] = predicted_ratings

    # 6. Get top recommendations (filter NaN titles and fix typo in 'predicted_rating')
    movies_not_watched = movies_not_watched[movies_not_watched['title'].notna()]
    top_recommendations = movies_not_watched.sort_values('predicted_rating', ascending=False).head(top_n)

    # 7. Create recommendations DataFrame
    recommendations_df = pd.DataFrame({
        'Title': top_recommendations['title'],
        'Genres': top_recommendations['genres'].apply(lambda x: ', '.join(x) if isinstance(x, list) else 'Unknown'),
        'Predicted Rating': top_recommendations['predicted_rating']
    })

    return watched_df, recommendations_df

# Contoh penggunaan
user_id = 2
watched_movies, recommended_movies = get_user_recommendations(user_id, svd)

# Tampilkan hasil
print(f"\n{'='*50}")
print(f"Film yang sudah ditonton oleh User {user_id}")
print('='*50)
watched_movies.loc[:]

print(f"\n{'='*50}")
print(f"Rekomendasi Film untuk User {user_id}")
print('='*50)
recommended_movies.loc[:]

"""## **Kesimpulan Sistem Rekomendasi Film**

### **1. Content-Based Filtering**
- **Metode**: Cosine Similarity berdasarkan metadata film  
- **Evaluasi**: NDCG@10 (Normalized Discounted Cumulative Gain)  
  - 🎬 The Dark Knight Rises: **0.9678**  
  - 🎬 The Godfather: **0.9791**  
- **Interpretasi**:  
  - Nilai ≈1.0 menunjukkan rekomendasi sangat relevan  

### **2. Collaborative Filtering (SVD)**  
- **Metode**: Matrix Factorization dengan SVD  
- **Evaluasi**:  
  - 📉 RMSE: **0.8959**  
  - 📊 MAE: **0.6893**  
- **Kelebihan**: Personalisasi berdasarkan riwayat rating user  

### **Perbandingan Performa**  
| Kriteria               | Content-Based       | Collaborative      |
|------------------------|---------------------|--------------------|
| **Metrik Evaluasi**    | NDCG@10 (0.96-0.97) | RMSE (0.89)        |
| **Kekuatan**           | Relevansi konten    | Personalisasi user |
| **Batasan**            | Cold-start problem  | Sparsity data      |

### **Rekomendasi Pengembangan**  
1. **Hybrid System**: Gabungkan kedua metode untuk:  
   - Relevansi konten (Content-Based)  
   - Personalisasi (Collaborative)  
2. **Improvement**:  
   - Tambah fitur film (sutradara, aktor)  
   - Gunakan deep learning untuk embedding  
"""